import SwiftUI
import HopPottyDesignTokens

// The HopPotty lockup, drawn from the product owner's artwork, in four layers
// that can each be moved on their own.
//
// ## Why paths and not an image
//
// SwiftUI cannot read SVG, so the artwork has to become *something* before it
// can be drawn. The usual answer is a vector PDF in the asset catalog, and it
// would have been the right one for a logo that only ever sits still. This one
// does not: the splash throws "Hop" in from the left, "Potty" in from the right
// and pops the frog up between them, which needs three things that can carry
// three different transforms — and an asset catalog image is one thing.
//
// Three PDFs would answer that, at the cost of three opaque binaries in the
// repository that no diff can review, that nothing verifies against the
// artwork, and that would have to be regenerated by hand from a tool this
// project does not have. `Scripts/logo-art.js` produces `HopLogoArtwork.swift`
// and the prototype's layer SVGs from one source in one run, and
// `Scripts/logo-check.js` proves the result is still the artwork. So the app
// and the web prototype are drawing the same curves, and the curves are text.
//
// The trade is real and worth naming: this is ~60 filled `Path`s rather than
// one image, and it is *drawn*, so the splash costs more than blitting a
// bitmap would. At the size and duration it is used — one screen, 1.55s, once
// per launch — that is far below anything a caregiver would notice, and the
// same drawing serves a 40pt mark if one is ever wanted.

// MARK: - The data the generator emits

/// One shape of the lockup: the artwork's own path, in the artwork's own
/// 164.8 × 95 units, with the fill and stroke it was drawn with.
struct HopLogoShape: Sendable, Equatable {
    /// Absolute `M` / `L` / `C` / `Z` — the only four commands the generator emits.
    let d: String
    let fill: UInt32?
    let stroke: UInt32?
    let strokeWidth: CGFloat
}

/// One layer: what it draws, and the outline it wears.
struct HopLogoLayerArt: Sendable {
    let shapes: [HopLogoShape]

    /// The layer's shapes as one path, every contour wound the same way, so
    /// filling it non-zero gives the layer's *solid* silhouette — counters of
    /// "o" and "p" included.
    ///
    /// This is the sticker edge. The artwork's own is a single fused contour
    /// around the whole lockup, which is exactly what a lockup that comes apart
    /// cannot use, so the generator rebuilds one per layer at the width and
    /// offset it measured from the original. `nil` for the tagline pill, which
    /// the artwork does not outline.
    let silhouette: String?

    /// What this layer actually covers, in artwork units — which is nowhere
    /// near the whole 164.8 × 95 box it is drawn in.
    ///
    /// The choreography needs it twice: to know how far off-screen a word has
    /// to start to be *fully* off-screen, and to find the line a word lands on,
    /// so its squash flattens onto its own baseline rather than about the
    /// middle of a box whose bottom edge belongs to the tagline pill.
    let bounds: CGRect
}

/// The four pieces of the lockup that move independently.
///
/// Declaration order **is** paint order, back to front, and it has to match
/// `PAINT_ORDER` in `Scripts/logo-art.js` — the header of the generated file
/// restates it for exactly that reason. The frog is under the wordmark rather
/// than over it so that it rises out from behind the letters instead of across
/// them; where the two overlap they are the same green, so nothing is lost.
enum HopLogoLayer: String, CaseIterable, Identifiable, Sendable {
    case tagline
    case mascot
    case hop
    case potty

    var id: String { rawValue }

    var art: HopLogoLayerArt {
        switch self {
        case .tagline: HopLogoArtwork.tagline
        case .mascot: HopLogoArtwork.mascot
        case .hop: HopLogoArtwork.hop
        case .potty: HopLogoArtwork.potty
        }
    }

    /// The line this layer rests on, as a fraction of the whole logo box's
    /// height.
    ///
    /// The same idea as ``HopCanvas/groundAnchor``: a thing that squashes about
    /// its own middle bobs, and a thing that squashes about its feet lands. The
    /// feet here are the bottom of the layer's own drawing — for "Hop" the
    /// baseline of the letters, not the bottom of a box that also has to
    /// contain the tagline pill 20 units lower.
    var groundAnchor: CGFloat {
        art.bounds.maxY / HopLogoArtwork.viewBox.height
    }

    /// How high this layer's hop arcs, as a fraction of the whole logo's height.
    ///
    /// `HopMotion.jumpHeightRatio` is a fraction of the *jumper's* own height —
    /// that is what keeps a hop the same size relative to the thing hopping at
    /// every scale — so it is applied to this layer's drawing, not to the box.
    var arcHeight: CGFloat {
        HopMotion.jumpHeightRatio * art.bounds.height / HopLogoArtwork.viewBox.height
    }
}

// MARK: - Path data → Path

extension HopLogoArtwork {

    /// Parses one generated path string.
    ///
    /// Deliberately not an SVG path parser. The generator resolves the
    /// exporter's relative commands, implicit repeats, shorthand curves and
    /// horizontal/vertical lines, and writes every segment with its own command
    /// letter, so the whole grammar this has to understand is four letters and a
    /// list of numbers. A malformed token yields a zero rather than a crash: a
    /// splash screen is the wrong place to trap, and the generator's own output
    /// is the only thing that ever reaches here.
    static func path(_ data: String) -> Path {
        var path = Path()
        var start = CGPoint.zero
        var tokens = data.split(separator: " ")[...]

        func number() -> CGFloat {
            guard let token = tokens.popFirst() else { return 0 }
            return CGFloat(Double(token) ?? 0)
        }
        func point() -> CGPoint {
            let x = number()
            return CGPoint(x: x, y: number())
        }

        while let command = tokens.popFirst() {
            switch command {
            case "M":
                start = point()
                path.move(to: start)
            case "L":
                path.addLine(to: point())
            case "C":
                let c1 = point(), c2 = point(), end = point()
                path.addCurve(to: end, control1: c1, control2: c2)
            case "Z":
                path.closeSubpath()
            default:
                break
            }
        }
        return path
    }

    /// Maps the artwork's box onto `rect`, fitting it and centring it.
    static func transform(fitting rect: CGRect) -> CGAffineTransform {
        let scale = min(rect.width / viewBox.width, rect.height / viewBox.height)
        return CGAffineTransform(
            translationX: rect.midX - viewBox.width * scale / 2,
            y: rect.midY - viewBox.height * scale / 2
        )
        .scaledBy(x: scale, y: scale)
    }
}

/// One path of the artwork, fitted to the view.
///
/// `outset` grows the shape by stroking it and adding the stroke back in. That
/// is how the sticker edge is drawn: the silhouette filled, plus the same
/// silhouette's outline, which unions to the silhouette pushed out by half the
/// width all round.
struct HopLogoPathShape: Shape {
    let data: String
    var outset: CGFloat = 0

    func path(in rect: CGRect) -> Path {
        var path = HopLogoArtwork.path(data)
        if outset > 0 {
            let edge = path.strokedPath(StrokeStyle(lineWidth: outset, lineCap: .round, lineJoin: .round))
            path.addPath(edge)
        }
        return path.applying(HopLogoArtwork.transform(fitting: rect))
    }
}

// MARK: - Where a layer sits

/// One layer's departure from where the artwork puts it.
///
/// Offsets are fractions of the logo's own width and height rather than points,
/// so one choreography reads the same on a 320pt phone and a 1024pt iPad, and
/// so the prototype's percentages and these numbers are literally the same
/// numbers.
struct HopLogoPlacement: Equatable, Sendable {
    /// Travel, as a fraction of the logo's width and height.
    var offset: CGSize = .zero
    /// Squash and stretch. Separate axes: a landing flattens, it does not shrink.
    var scaleX: CGFloat = 1
    var scaleY: CGFloat = 1
    var opacity: Double = 1
    /// The height the scale is anchored at, as a fraction of the logo box. A
    /// word lands *on* its baseline; see ``HopLogoLayer/groundAnchor``. A
    /// fraction rather than a `UnitPoint` so this whole type stays a handful of
    /// numbers that any context can hold.
    var anchor: CGFloat = 0.5

    /// Exactly where the artwork draws it.
    static let placed = HopLogoPlacement()
}

/// Where all four layers sit. `assembled` is the finished lockup.
struct HopLogoLayout: Equatable, Sendable {
    var tagline: HopLogoPlacement = .placed
    var mascot: HopLogoPlacement = .placed
    var hop: HopLogoPlacement = .placed
    var potty: HopLogoPlacement = .placed

    static let assembled = HopLogoLayout()

    subscript(layer: HopLogoLayer) -> HopLogoPlacement {
        get {
            switch layer {
            case .tagline: tagline
            case .mascot: mascot
            case .hop: hop
            case .potty: potty
            }
        }
        set {
            switch layer {
            case .tagline: tagline = newValue
            case .mascot: mascot = newValue
            case .hop: hop = newValue
            case .potty: potty = newValue
            }
        }
    }
}

// MARK: - The view

/// The lockup, at `width`, with each layer wherever `layout` puts it.
///
/// ## Two passes, and why
///
/// Every sticker edge is drawn first, then every fill. Drawing each layer
/// complete — its own edge, then its own fills — would put the frog's white
/// edge *on top of* the wordmark, and the letters would grow a white bite out
/// of their crowns. Two passes keeps each layer's edge travelling with it while
/// the four edges still merge underneath the artwork once everything has
/// landed, which is what the original single fused silhouette does.
///
/// The colours are literals from the artwork, not theme tokens: a brand mark
/// that changes colour with the appearance is not a brand mark. It reads
/// correctly on both grounds because the sticker edge is what separates it from
/// either one.
struct HopLogoView: View {
    let width: CGFloat
    var layout: HopLogoLayout = .assembled

    /// One artwork unit, in points.
    private var unit: CGFloat { width / HopLogoArtwork.viewBox.width }
    private var height: CGFloat { HopLogoArtwork.viewBox.height * unit }
    private var backing: Color { Color(HopColorValue(hex: HopLogoArtwork.backingColor)) }

    var body: some View {
        ZStack {
            ForEach(HopLogoLayer.allCases) { silhouette(of: $0) }
            ForEach(HopLogoLayer.allCases) { artwork(of: $0) }
        }
        .frame(width: width, height: height)
        // One label for the whole lockup, and no children: the frog, the two
        // words and the pill are one mark, and forty paths are forty
        // meaningless stops for anyone reading with VoiceOver.
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(HopStrings.logo)
        .accessibilityAddTraits(.isImage)
    }

    /// The rebuilt sticker edge: the shadow copy, then the outline over it.
    /// Both are the one flat colour the artwork flattened them into.
    @ViewBuilder
    private func silhouette(of layer: HopLogoLayer) -> some View {
        if let data = layer.art.silhouette {
            let edge = HopLogoPathShape(data: data, outset: HopLogoArtwork.outlineWidth)
            ZStack {
                edge.fill(backing)
                    .offset(y: HopLogoArtwork.shadowOffset * unit)
                edge.fill(backing)
            }
            .frame(width: width, height: height)
            .modifier(HopLogoPlacementModifier(placement: layout[layer], size: CGSize(width: width, height: height)))
        }
    }

    private func artwork(of layer: HopLogoLayer) -> some View {
        ZStack {
            ForEach(Array(layer.art.shapes.enumerated()), id: \.offset) { _, shape in
                draw(shape)
            }
        }
        .frame(width: width, height: height)
        .modifier(HopLogoPlacementModifier(placement: layout[layer], size: CGSize(width: width, height: height)))
    }

    /// One shape: its fill, then its stroke. Two of the fifty-eight are strokes
    /// with no fill (the frog's arms), which is why both are optional.
    @ViewBuilder
    private func draw(_ shape: HopLogoShape) -> some View {
        let path = HopLogoPathShape(data: shape.d)
        ZStack {
            if let fill = shape.fill {
                path.fill(Color(HopColorValue(hex: fill)))
            }
            if let stroke = shape.stroke {
                path.stroke(
                    Color(HopColorValue(hex: stroke)),
                    style: StrokeStyle(lineWidth: shape.strokeWidth * unit, lineCap: .round)
                )
            }
        }
    }
}

/// Scale about the placement's anchor, then travel, then fade.
///
/// The order is the point: scaling after the offset would move the layer's
/// anchor with it, and a word that squashes about a moving point wobbles
/// instead of landing.
private struct HopLogoPlacementModifier: ViewModifier {
    let placement: HopLogoPlacement
    let size: CGSize

    func body(content: Content) -> some View {
        content
            .scaleEffect(x: placement.scaleX, y: placement.scaleY,
                         anchor: UnitPoint(x: 0.5, y: placement.anchor))
            .offset(x: placement.offset.width * size.width, y: placement.offset.height * size.height)
            .opacity(placement.opacity)
    }
}

#if DEBUG
#Preview("Lockup") {
    HopThemedRoot {
        VStack(spacing: 32) {
            HopLogoView(width: 300)
            HopLogoView(width: 140)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .hopBackground()
    }
}
#endif
