#!/usr/bin/env node
/**
 * Generates Hop's React Native scene graph from the existing art rig.
 *
 * ## Why generated rather than redrawn
 *
 * `Scripts/hop-art.js` is the mascot rig: fifteen poses built from shared
 * anatomy, held to the silhouette, fit and cross-language contract gates. It is
 * already JavaScript, and it already emits named groups — `head`, `left-pupil`,
 * `right-arm`, `mouth` — which is precisely what an animatable React Native
 * character needs.
 *
 * Redrawing Hop in TSX would fork the character: two drawings, two sets of
 * geometry, and a gate that can only check one of them. Instead the rig's own
 * SVG output is parsed at BUILD time into a typed scene graph. Runtime does no
 * parsing, the geometry is provably the rig's, and `--check` fails if the two
 * ever diverge.
 *
 * `SvgXml` was rejected for the same reason it is tempting: it would render the
 * rig's string directly, but re-parse on every prop change and expose no handle
 * on `left-pupil`, so blinking, gaze and a waving arm would all be impossible.
 * A structured tree keeps every part addressable.
 *
 *   Scripts/rn/build-mascot.js          regenerate
 *   Scripts/rn/build-mascot.js --check  verify, change nothing
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const art = require(path.join(ROOT, 'Scripts', 'hop-art.js'));
const OUT = path.join(ROOT, 'src', 'mascot', 'poses.generated.ts');

// react-native-svg takes camelCase props. The rig writes SVG attribute names.
const PROP = {
  'stroke-width': 'strokeWidth', 'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin', 'stroke-opacity': 'strokeOpacity',
  'stroke-dasharray': 'strokeDasharray', 'fill-opacity': 'fillOpacity',
  'fill-rule': 'fillRule', 'clip-path': 'clipPath', 'clip-rule': 'clipRule',
  'stop-color': 'stopColor', 'stop-opacity': 'stopOpacity',
  'font-family': 'fontFamily', 'font-size': 'fontSize', 'font-weight': 'fontWeight',
  'text-anchor': 'textAnchor', 'letter-spacing': 'letterSpacing',
};

/**
 * A deliberately small parser for the rig's own output.
 *
 * Not a general SVG parser and not trying to be: the input is generated by a
 * script in this repository, so it is well-formed, unquoted-attribute-free and
 * has no comments, CDATA or namespaces beyond the root. Pulling in a DOM
 * library to read our own output would be the larger risk.
 */
function parse(svg) {
  // One regex over a tag-only document. The rig emits no text nodes, comments
  // or CDATA — it is generated by a sibling script — so a tokeniser is both
  // sufficient and far harder to get subtly wrong than walking indices.
  const TAG = /<(\/?)([A-Za-z][\w:-]*)((?:\s+[\w:-]+="[^"]*")*)\s*(\/?)>/g;
  const root = { t: '#root', p: {}, c: [] };
  const stack = [root];
  let m;
  let consumed = 0;
  while ((m = TAG.exec(svg)) !== null) {
    const [full, closing, name, attrs, selfClose] = m;
    // Text between tags belongs to the element currently open — the `sleep`
    // pose draws its "Zzz" as two <text>z</text> nodes. Anything else here
    // would mean this is not the document we think it is, and silently
    // dropping it would corrupt the character.
    const between = svg.slice(consumed, m.index);
    if (between.trim()) {
      const open = stack[stack.length - 1];
      if (open === root) throw new Error(`text outside the root: ${JSON.stringify(between.trim())}`);
      open.x = (open.x ?? '') + between.trim();
    }
    consumed = m.index + full.length;

    if (closing) {
      const open = stack.pop();
      if (!open || open.t !== name) {
        throw new Error(`mismatched </${name}> (open was ${open ? open.t : 'nothing'})`);
      }
      continue;
    }
    const props = {};
    for (const a of attrs.matchAll(/([\w:-]+)="([^"]*)"/g)) {
      props[PROP[a[1]] ?? a[1]] = a[2];
    }
    const node = { t: name, p: props };
    (stack[stack.length - 1].c ??= []).push(node);
    if (!selfClose) { node.c = []; stack.push(node); }
  }
  if (stack.length !== 1) throw new Error(`${stack.length - 1} unclosed element(s)`);
  const tail = svg.slice(consumed);
  if (tail.trim()) throw new Error(`trailing text ${JSON.stringify(tail.trim().slice(0, 40))}`);
  if (root.c.length !== 1) throw new Error(`expected one root element, got ${root.c.length}`);
  // Empty child arrays would serialise as noise.
  const prune = (n) => { if (n.c) { if (!n.c.length) delete n.c; else n.c.forEach(prune); } return n; };
  return prune(root.c[0]);
}

/** Numeric-looking attribute values become numbers, so RN skips a parse. */
function tighten(node) {
  const p = {};
  for (const [k, v] of Object.entries(node.p)) {
    if (k === 'xmlns') continue;
    p[k] = /^-?\d+(\.\d+)?$/.test(v) ? Number(v) : v;
  }
  const out = { t: node.t, p };
  if (node.x !== undefined) out.x = node.x;
  if (node.c) out.c = node.c.map(tighten);
  return out;
}

/**
 * Proves the scene graph is the rig's drawing, not a lookalike.
 *
 * The tree builder is the part of this script that could plausibly be wrong —
 * dropping a node, reordering siblings, losing an attribute. So the check does
 * not reuse it: it scans the rig's SVG with a flat regex and compares that
 * sequence, element for element and attribute for attribute, against a walk of
 * the tree. If Hop ever stops matching the rig, this fails at build time rather
 * than shipping a subtly wrong character.
 */
function verifyFaithful(name, svg, tree) {
  const flatten = (node, out = []) => {
    const keys = Object.keys(node.p).sort();
    out.push(`${node.t}|${keys.map((k) => `${k}=${node.p[k]}`).join(',')}`);
    (node.c ?? []).forEach((c) => flatten(c, out));
    return out;
  };
  const fromTree = flatten(tree);

  const fromScan = [];
  for (const m of svg.matchAll(/<(?!\/)([A-Za-z][\w:-]*)((?:\s+[\w:-]+="[^"]*")*)\s*\/?>/g)) {
    if (m[1] === 'svg') continue; // the wrapper is not shipped
    const props = {};
    for (const a of m[2].matchAll(/([\w:-]+)="([^"]*)"/g)) {
      if (a[1] === 'xmlns') continue;
      const v = a[2];
      props[PROP[a[1]] ?? a[1]] = /^-?\d+(\.\d+)?$/.test(v) ? Number(v) : v;
    }
    const keys = Object.keys(props).sort();
    fromScan.push(`${m[1]}|${keys.map((k) => `${k}=${props[k]}`).join(',')}`);
  }

  if (fromTree.length !== fromScan.length) {
    throw new Error(`${name}: tree has ${fromTree.length} elements, the rig drew ${fromScan.length}`);
  }
  for (let i = 0; i < fromTree.length; i += 1) {
    if (fromTree[i] !== fromScan[i]) {
      throw new Error(`${name}: element ${i} differs\n  tree: ${fromTree[i]}\n  rig:  ${fromScan[i]}`);
    }
  }
  return fromTree.length;
}

const poses = {};
let elementCount = 0;
for (const name of art.POSE_NAMES) {
  const svg = art.poseSVG(name);
  const parsed = tighten(parse(svg));
  // The <svg> wrapper carries only the viewBox, which is constant and lives on
  // the component instead; the tree we ship starts at its single child.
  const root = parsed.t === 'svg' && parsed.c && parsed.c.length === 1 ? parsed.c[0] : parsed;
  elementCount += verifyFaithful(name, svg, root);
  poses[name] = root;
}

const partIds = [...new Set(
  JSON.stringify(poses).match(/"id":"([^"]+)"/g)?.map((s) => s.slice(6, -1)) ?? []
)].sort();

const lines = [];
lines.push('/**');
lines.push(' * GENERATED FILE — DO NOT EDIT.');
lines.push(' *');
lines.push(' * Hop\'s pose geometry, parsed from the art rig (Scripts/hop-art.js) at build');
lines.push(' * time so React Native renders the same character the app and the render');
lines.push(' * harness draw, from the same source.');
lines.push(' *');
lines.push(' * Regenerate:  node Scripts/rn/build-mascot.js');
lines.push(' * Verify:      node Scripts/rn/build-mascot.js --check');
lines.push(' */');
lines.push('');
lines.push('/** One SVG element: tag, props, children. */');
lines.push('export interface HopNode {');
lines.push('  readonly t: string;');
lines.push('  readonly p: Readonly<Record<string, string | number>>;');
lines.push('  /** Literal text content — only the sleep pose\'s "Zzz" uses this. */');
lines.push('  readonly x?: string;');
lines.push('  readonly c?: readonly HopNode[];');
lines.push('}');
lines.push('');
lines.push(`export const HOP_VIEWBOX = ${art.CANVAS};`);
lines.push('');
lines.push('/** Feet sit this far down the canvas — used to seat Hop on a baseline. */');
lines.push(`export const HOP_FEET_FRACTION = ${art.FEET_FRACTION};`);
lines.push('');
lines.push(`export type HopPoseName = ${art.POSE_NAMES.map((p) => JSON.stringify(p)).join(' | ')};`);
lines.push('');
lines.push('/** Every addressable part id the rig emits, for animation targeting. */');
lines.push(`export type HopPartId = ${partIds.map((p) => JSON.stringify(p)).join(' | ')};`);
lines.push('');
lines.push('export const HOP_POSES: Readonly<Record<HopPoseName, HopNode>> = ');
lines.push(JSON.stringify(poses) + ';');
lines.push('');

const out = lines.join('\n');
const check = process.argv.includes('--check');
const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;

if (check) {
  if (existing !== out) {
    console.error('STALE: the React Native mascot no longer matches the art rig.');
    console.error('       run: node Scripts/rn/build-mascot.js');
    process.exit(1);
  }
  console.log(`react native mascot: current  (${art.POSE_NAMES.length} poses, ${partIds.length} named parts, ${elementCount} elements verified against the rig)`);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);
  const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
  console.log(`wrote src/mascot/poses.generated.ts  (${art.POSE_NAMES.length} poses, ${partIds.length} named parts, ${kb} KB)`);
  console.log(`  ${elementCount} elements verified identical to the rig`);
}
